// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7sSTzDJrJ5DmTdkrIXI4E3cIJv5c7Fjo',
    appId: '1:758440657972:web:eaeba69f6ee5046863b661',
    messagingSenderId: '758440657972',
    projectId: 'love-chat-f93fa',
    authDomain: 'love-chat-f93fa.firebaseapp.com',
    storageBucket: 'love-chat-f93fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAytswHhZV4zH0H-JfqjXCW6YMAW16n1N8',
    appId: '1:758440657972:android:5036c2618992603c63b661',
    messagingSenderId: '758440657972',
    projectId: 'love-chat-f93fa',
    storageBucket: 'love-chat-f93fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDztoM5BtbMNkLgWo1rsdtcEwlaOxm6PbQ',
    appId: '1:758440657972:ios:e3c3eff18db079d463b661',
    messagingSenderId: '758440657972',
    projectId: 'love-chat-f93fa',
    storageBucket: 'love-chat-f93fa.firebasestorage.app',
    iosClientId: '758440657972-rsggmimo7dk3djun33rb6bveq4hmgkdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveChat',
  );
}
